apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.name }}
  template:
    metadata:
      labels:
        app: ${{ values.name }}
        backstage.io/kubernetes-id: ${{ values.name }}
    spec:
      containers:
        - name: app
          image: ghcr.io/rohitpandey1995/${{ values.name }}:latest
